# Generated by Django 5.2 on 2025-04-17 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
